FROM php:8.2-fpm

# Installer les dépendances pour PostgreSQL et extensions PHP
RUN apt-get update && apt-get install -y \
        libpq-dev \
        git \
        unzip \
        curl \
    && docker-php-ext-install pdo_pgsql

# Installer Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www
